name = "forray"
version = "1.0.0"
license = "MIT"
author = "jordan4ibanez"
maintainer = "jordan4ibanez"
copyright = "Copyright 2024, jordan4ibanez"

[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false

[dependencies]
string_f90 = { git = "https://github.com/jordan4ibanez/string_f90" }

[install]
library = false

[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"
